2022-06-12 03:19:39,842 INFO    MainThread:37116 [wandb_setup.py:_flush():76] Loading settings from C:\Users\19423\.config\wandb\settings
2022-06-12 03:19:39,842 INFO    MainThread:37116 [wandb_setup.py:_flush():76] Loading settings from D:\Projects\DeepLearning\Demo\wandb\settings
2022-06-12 03:19:39,842 INFO    MainThread:37116 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-06-12 03:19:39,842 INFO    MainThread:37116 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-06-12 03:19:39,842 WARNING MainThread:37116 [wandb_setup.py:_flush():76] interrupted
Traceback (most recent call last):
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\19423\AppData\Local\Temp\ipykernel_37116\2052378596.py", line 118, in <cell line: 118>
    wandb.init(project="kaggle_predict",
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\wandb\sdk\wandb_init.py", line 1021, in init
    raise e
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\wandb\sdk\wandb_init.py", line 996, in init
    wi.setup(kwargs)
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\wandb\sdk\wandb_init.py", line 237, in setup
    wandb_login._login(
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\wandb\sdk\wandb_login.py", line 297, in _login
    wlogin.prompt_api_key()
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\wandb\sdk\wandb_login.py", line 220, in prompt_api_key
    key, status = self._prompt_api_key()
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\wandb\sdk\wandb_login.py", line 200, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\wandb\sdk\lib\apikey.py", line 130, in prompt_api_key
    key = input_callback(api_ask).strip()
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\ipykernel\kernelbase.py", line 1143, in getpass
    return self._input_request(
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\ipykernel\kernelbase.py", line 1205, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
2022-06-12 03:19:39,842 INFO    MainThread:37116 [wandb_init.py:_log_setup():428] Logging user logs to D:\Projects\DeepLearning\Demo\wandb\run-20220612_031939-2vry32y1\logs\debug.log
2022-06-12 03:19:39,842 INFO    MainThread:37116 [wandb_init.py:_log_setup():429] Logging internal logs to D:\Projects\DeepLearning\Demo\wandb\run-20220612_031939-2vry32y1\logs\debug-internal.log
2022-06-12 03:19:39,842 INFO    MainThread:37116 [wandb_init.py:_jupyter_setup():378] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000166ADB4A6D0>
2022-06-12 03:19:39,842 INFO    MainThread:37116 [wandb_init.py:init():462] calling init triggers
2022-06-12 03:19:39,842 INFO    MainThread:37116 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.005, 'weight_decay': 0.05, 'batch_size': 256, 'total_run': 2000, 'network': 'in->256->64'}
2022-06-12 03:19:39,842 INFO    MainThread:37116 [wandb_init.py:init():515] starting backend
2022-06-12 03:19:39,842 INFO    MainThread:37116 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2022-06-12 03:19:39,850 INFO    MainThread:37116 [backend.py:ensure_launched():217] starting backend process...
2022-06-12 03:19:39,923 INFO    MainThread:37116 [backend.py:ensure_launched():222] started backend process with pid: 14552
2022-06-12 03:19:39,923 INFO    MainThread:37116 [wandb_init.py:init():525] backend started and connected
2022-06-12 03:19:39,933 INFO    MainThread:37116 [wandb_run.py:_label_probe_notebook():1089] probe notebook
2022-06-12 03:19:39,935 INFO    MainThread:37116 [wandb_run.py:_label_probe_notebook():1099] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-06-12 03:19:39,935 INFO    MainThread:37116 [wandb_init.py:init():596] updated telemetry
2022-06-12 03:19:39,992 INFO    MainThread:37116 [wandb_init.py:init():627] communicating run to backend with 30 second timeout
2022-06-12 03:19:41,547 INFO    MainThread:37116 [wandb_run.py:_on_init():1924] communicating current version
2022-06-12 03:19:41,831 INFO    MainThread:37116 [wandb_run.py:_on_init():1928] got version response 
2022-06-12 03:19:41,832 INFO    MainThread:37116 [wandb_init.py:init():662] starting run threads in backend
2022-06-12 03:19:44,053 INFO    MainThread:37116 [wandb_run.py:_console_start():1898] atexit reg
2022-06-12 03:19:44,054 INFO    MainThread:37116 [wandb_run.py:_redirect():1771] redirect: SettingsConsole.WRAP
2022-06-12 03:19:44,054 INFO    MainThread:37116 [wandb_run.py:_redirect():1808] Wrapping output streams.
2022-06-12 03:19:44,056 INFO    MainThread:37116 [wandb_run.py:_redirect():1832] Redirects installed.
2022-06-12 03:19:44,056 INFO    MainThread:37116 [wandb_init.py:init():688] run started, returning control to user process
2022-06-12 03:19:44,056 INFO    MainThread:37116 [wandb_init.py:_pause_backend():341] pausing backend
2022-06-12 03:19:44,057 INFO    MainThread:37116 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-06-12 03:23:37,519 INFO    MainThread:37116 [wandb_init.py:_resume_backend():350] resuming backend
2022-06-12 03:23:39,282 INFO    MainThread:37116 [wandb_setup.py:_flush():76] Loading settings from C:\Users\19423\.config\wandb\settings
2022-06-12 03:23:39,282 INFO    MainThread:37116 [wandb_setup.py:_flush():76] Loading settings from D:\Projects\DeepLearning\Demo\wandb\settings
2022-06-12 03:23:39,282 INFO    MainThread:37116 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-06-12 03:23:39,282 INFO    MainThread:37116 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-06-12 03:23:39,282 WARNING MainThread:37116 [wandb_setup.py:_flush():76] interrupted
Traceback (most recent call last):
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\19423\AppData\Local\Temp\ipykernel_37116\2052378596.py", line 118, in <cell line: 118>
    wandb.init(project="kaggle_predict",
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\wandb\sdk\wandb_init.py", line 1021, in init
    raise e
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\wandb\sdk\wandb_init.py", line 996, in init
    wi.setup(kwargs)
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\wandb\sdk\wandb_init.py", line 237, in setup
    wandb_login._login(
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\wandb\sdk\wandb_login.py", line 297, in _login
    wlogin.prompt_api_key()
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\wandb\sdk\wandb_login.py", line 220, in prompt_api_key
    key, status = self._prompt_api_key()
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\wandb\sdk\wandb_login.py", line 200, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\wandb\sdk\lib\apikey.py", line 130, in prompt_api_key
    key = input_callback(api_ask).strip()
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\ipykernel\kernelbase.py", line 1143, in getpass
    return self._input_request(
  File "C:\Users\19423\.conda\envs\nlp\lib\site-packages\ipykernel\kernelbase.py", line 1205, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
2022-06-12 03:23:39,284 INFO    MainThread:37116 [wandb_init.py:_log_setup():428] Logging user logs to D:\Projects\DeepLearning\Demo\wandb\run-20220612_032339-246n5ot1\logs\debug.log
2022-06-12 03:23:39,284 INFO    MainThread:37116 [wandb_init.py:_log_setup():429] Logging internal logs to D:\Projects\DeepLearning\Demo\wandb\run-20220612_032339-246n5ot1\logs\debug-internal.log
2022-06-12 03:23:39,284 INFO    MainThread:37116 [wandb_init.py:init():462] calling init triggers
2022-06-12 03:23:39,284 INFO    MainThread:37116 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.005, 'weight_decay': 0.05, 'batch_size': 256, 'total_run': 2000, 'network': 'in->256->64'}
2022-06-12 03:23:39,284 INFO    MainThread:37116 [wandb_init.py:init():481] re-initializing run, found existing run on stack: 2vry32y1
2022-06-12 03:23:39,286 INFO    MainThread:37116 [wandb_run.py:_finish():1685] finishing run moye12325/kaggle_predict/2vry32y1
2022-06-12 03:23:39,287 INFO    MainThread:37116 [jupyter.py:save_history():435] not saving jupyter history
2022-06-12 03:23:39,287 INFO    MainThread:37116 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-06-12 03:23:39,287 INFO    MainThread:37116 [wandb_init.py:_jupyter_teardown():360] cleaning up jupyter logic
2022-06-12 03:23:39,287 INFO    MainThread:37116 [wandb_run.py:_atexit_cleanup():1867] got exitcode: 0
2022-06-12 03:23:39,288 INFO    MainThread:37116 [wandb_run.py:_restore():1839] restore
2022-06-12 03:23:39,948 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-06-12 03:23:40,402 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-06-12 03:23:40,566 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 32454
}

2022-06-12 03:23:40,680 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 32480
}

2022-06-12 03:23:40,788 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 32480
}

2022-06-12 03:23:40,896 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 32480
}

2022-06-12 03:23:41,005 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 32480
}

2022-06-12 03:23:41,113 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 26212
  total_bytes: 32480
}

2022-06-12 03:23:41,222 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28353
  total_bytes: 32480
}

2022-06-12 03:23:41,330 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 28353
  total_bytes: 32480
}

2022-06-12 03:23:41,438 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 32480
  total_bytes: 32480
}

2022-06-12 03:23:41,550 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 32480
  total_bytes: 32480
}

2022-06-12 03:23:41,657 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 32480
  total_bytes: 32480
}

2022-06-12 03:23:41,768 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 32480
  total_bytes: 32480
}

2022-06-12 03:23:41,876 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 32480
  total_bytes: 32480
}

2022-06-12 03:23:42,688 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 32480
  total_bytes: 32480
}

2022-06-12 03:23:43,437 INFO    MainThread:37116 [wandb_run.py:_on_finish():1996] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 32480
  total_bytes: 32480
}
local_info {
}

2022-06-12 03:23:44,572 INFO    MainThread:37116 [wandb_run.py:_footer_history_summary_info():3104] rendering history
2022-06-12 03:23:44,572 INFO    MainThread:37116 [wandb_run.py:_footer_history_summary_info():3136] rendering summary
2022-06-12 03:23:44,575 INFO    MainThread:37116 [wandb_run.py:_footer_sync_info():3060] logging synced files
